CREATE TABLE cliente(
    cliente_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    apellido VARCHAR(255) NOT NULL,
    telefono VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    direccion VARCHAR(255) NOT NULL,
    identificacion BIGINT NOT NULL
);

CREATE TABLE pedido(
    pedido_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    fecha DATETIME NOT NULL,
    cliente_id BIGINT NOT NULL,
    estatoPedido_id BIGINT NOT NULL,
    producto_id BIGINT NOT NULL,
    cantidad BIGINT NOT NULL
);
CREATE TABLE producto(
    id_producto BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    proveedor_preferido BIGINT NOT NULL,
    color BIGINT NOT NULL,
    tallas BIGINT NOT NULL
);
CREATE TABLE pagos(
    id_pagos BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    fecha DATETIME NOT NULL,
    factura_id INT NOT NULL,
    metodoPago_id INT NOT NULL
);
CREATE TABLE estado_pedido(
    id_estadoP BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre BIGINT NOT NULL
);
CREATE TABLE metodo_pago(
    id_metodoPago BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    descripcion VARCHAR(255) NOT NULL
);
CREATE TABLE factura(
    id_factura INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    fecha DATETIME NOT NULL,
    clienteID INT NOT NULL,
    detalles VARCHAR(255) NOT NULL,
    Pedido_id BIGINT NOT NULL
);
CREATE TABLE proveedor(
    id_proveedor BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    direccion VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    telefono VARCHAR(255) NOT NULL
);

CREATE TABLE pedidos_pendientes(
    id_pedidos BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    producto_id BIGINT NOT NULL,
    cantidad INT NOT NULL,
    proveedor_id INT NOT NULL,
    fecha DATETIME NOT NULL
);
CREATE TABLE inventario(
    id_inventario BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    producto_id BIGINT NOT NULL,
    cantidad DOUBLE(8, 2) NOT NULL,
    provedorID BIGINT NOT NULL
);
